name: CI Kasir Sederhana

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Dependency
      run: sudo apt-get install -y g++

    - name: Compile tes.cpp
      run: g++ -o main Dadu.cpp

    - name: Create Input File
      run: echo "6" > input.txt

    - name: Run the program
      run: ./main
